/*
 *	The MIT License (MIT)
 *
 *	Copyright (c) 2017 Jerry Lee
 *
 *	Permission is hereby granted, free of charge, to any person obtaining a copy
 *	of this software and associated documentation files (the "Software"), to deal
 *	in the Software without restriction, including without limitation the rights
 *	to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 *	copies of the Software, and to permit persons to whom the Software is
 *	furnished to do so, subject to the following conditions:
 *
 *	The above copyright notice and this permission notice shall be included in all
 *	copies or substantial portions of the Software.
 *
 *	THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 *	IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 *	FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 *	AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 *	LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 *	OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 *	SOFTWARE.
 */

using QuickUnity.Data;

namespace Tests.UnitTests.Editor.Data
{
    /// <summary>
    /// TestData
	/// Note: Generated by Editor automatically. Please don't edit this file manually!
    /// </summary>
    public class TestData : DataTableRow
    {
		/// <summary>
		/// ID
		/// </summary>
		public long Id;

		/// <summary>
		/// 测试布尔
		/// test bool
		/// </summary>
		public bool TestBoolean;

		/// <summary>
		/// test byte
		/// </summary>
		public byte TestByte;

		/// <summary>
		/// test sbyte
		/// </summary>
		public sbyte TestSByte;

		/// <summary>
		/// test short
		/// </summary>
		public short TestShort;

		/// <summary>
		/// test ushort
		/// </summary>
		public ushort TestUShort;

		/// <summary>
		/// test int
		/// </summary>
		public int TestInt;

		/// <summary>
		/// test uint
		/// </summary>
		public uint TestUInt;

		/// <summary>
		/// test ulong
		/// </summary>
		public ulong TestULong;

		/// <summary>
		/// test float
		/// </summary>
		public float TestFloat;

		/// <summary>
		/// test double
		/// </summary>
		public double TestDouble;

		/// <summary>
		/// test decimal
		/// </summary>
		public decimal TestDecimal;

		/// <summary>
		/// test string
		/// </summary>
		public string TestString;

		/// <summary>
		/// 测试Vector2
		/// </summary>
		public string TestVector2;

		/// <summary>
		/// 测试Vector3
		/// </summary>
		public string TestVector3;

		/// <summary>
		/// 测试Quaternion
		/// </summary>
		public string TestQuaternion;

		/// <summary>
		/// 测试booleanArray
		/// </summary>
		public bool[] TestBooleanArray;

		/// <summary>
		/// 测试byteArray
		/// </summary>
		public byte[] TestByteArray;

		/// <summary>
		/// 测试sbyteArray
		/// </summary>
		public sbyte[] TestSByteArray;

		/// <summary>
		/// 测试shortArray
		/// </summary>
		public short[] TestShortArray;

		/// <summary>
		/// 测试ushortArray
		/// </summary>
		public ushort[] TestUShortArray;

		/// <summary>
		/// 测试intArray
		/// </summary>
		public int[] TestIntArray;

		/// <summary>
		/// 测试uintArray
		/// </summary>
		public uint[] TestUIntArray;

		/// <summary>
		/// 测试longArray
		/// </summary>
		public long[] TestLongArray;

		/// <summary>
		/// 测试ulongArray
		/// </summary>
		public ulong[] TestULongArray;

		/// <summary>
		/// 测试floatArray
		/// </summary>
		public float[] TestFloatArray;

		/// <summary>
		/// 测试doubleArray
		/// </summary>
		public double[] TestDoubleArray;

		/// <summary>
		/// 测试decimalArray
		/// </summary>
		public decimal[] TestDecimalArray;

		/// <summary>
		/// 测试stringArray
		/// </summary>
		public string[] TestStringArray;

		/// <summary>
        /// Initializes a new instance of the <see cref="TestData"/> class.
        /// </summary>
        public TestData()
            : base()
        {
        }
    }
}