/*
 *	The MIT License (MIT)
 *
 *	Copyright (c) 2017 Jerry Lee
 *
 *	Permission is hereby granted, free of charge, to any person obtaining a copy
 *	of this software and associated documentation files (the "Software"), to deal
 *	in the Software without restriction, including without limitation the rights
 *	to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 *	copies of the Software, and to permit persons to whom the Software is
 *	furnished to do so, subject to the following conditions:
 *
 *	The above copyright notice and this permission notice shall be included in all
 *	copies or substantial portions of the Software.
 *
 *	THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 *	IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 *	FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 *	AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 *	LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 *	OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 *	SOFTWARE.
 */

using QuickUnity.Data;

namespace Tests.UnitTests.Editor.Data
{
    /// <summary>
    /// TestData
	/// Note: Generated by Editor automatically. Please don't edit this file manually!
    /// </summary>
    public class TestData : DataTableRow
    {
		/// <summary>
		/// ID
		/// </summary>
		public long Id
		{
			get;
			set;
		}

		/// <summary>
		/// 测试布尔
		/// test bool
		/// </summary>
		public bool TestBoolean
		{
			get;
			set;
		}

		/// <summary>
		/// test byte
		/// </summary>
		public byte TestByte
		{
			get;
			set;
		}

		/// <summary>
		/// test sbyte
		/// </summary>
		public sbyte TestSByte
		{
			get;
			set;
		}

		/// <summary>
		/// test short
		/// </summary>
		public short TestShort
		{
			get;
			set;
		}

		/// <summary>
		/// test ushort
		/// </summary>
		public ushort TestUShort
		{
			get;
			set;
		}

		/// <summary>
		/// test int
		/// </summary>
		public int TestInt
		{
			get;
			set;
		}

		/// <summary>
		/// test uint
		/// </summary>
		public uint TestUInt
		{
			get;
			set;
		}

		/// <summary>
		/// test ulong
		/// </summary>
		public ulong TestULong
		{
			get;
			set;
		}

		/// <summary>
		/// test float
		/// </summary>
		public float TestFloat
		{
			get;
			set;
		}

		/// <summary>
		/// test double
		/// </summary>
		public double TestDouble
		{
			get;
			set;
		}

		/// <summary>
		/// test decimal
		/// </summary>
		public decimal TestDecimal
		{
			get;
			set;
		}

		/// <summary>
		/// test string
		/// </summary>
		public string TestString
		{
			get;
			set;
		}

		/// <summary>
		/// 测试Vector2
		/// </summary>
		public string TestVector2
		{
			get;
			set;
		}

		/// <summary>
		/// 测试Vector3
		/// </summary>
		public string TestVector3
		{
			get;
			set;
		}

		/// <summary>
		/// 测试Quaternion
		/// </summary>
		public string TestQuaternion
		{
			get;
			set;
		}

		/// <summary>
		/// 测试booleanArray
		/// </summary>
		public bool[] TestBooleanArray
		{
			get;
			set;
		}

		/// <summary>
		/// 测试byteArray
		/// </summary>
		public byte[] TestByteArray
		{
			get;
			set;
		}

		/// <summary>
		/// 测试sbyteArray
		/// </summary>
		public sbyte[] TestSByteArray
		{
			get;
			set;
		}

		/// <summary>
		/// 测试shortArray
		/// </summary>
		public short[] TestShortArray
		{
			get;
			set;
		}

		/// <summary>
		/// 测试ushortArray
		/// </summary>
		public ushort[] TestUShortArray
		{
			get;
			set;
		}

		/// <summary>
		/// 测试intArray
		/// </summary>
		public int[] TestIntArray
		{
			get;
			set;
		}

		/// <summary>
		/// 测试uintArray
		/// </summary>
		public uint[] TestUIntArray
		{
			get;
			set;
		}

		/// <summary>
		/// 测试longArray
		/// </summary>
		public long[] TestLongArray
		{
			get;
			set;
		}

		/// <summary>
		/// 测试ulongArray
		/// </summary>
		public ulong[] TestULongArray
		{
			get;
			set;
		}

		/// <summary>
		/// 测试floatArray
		/// </summary>
		public float[] TestFloatArray
		{
			get;
			set;
		}

		/// <summary>
		/// 测试doubleArray
		/// </summary>
		public double[] TestDoubleArray
		{
			get;
			set;
		}

		/// <summary>
		/// 测试decimalArray
		/// </summary>
		public decimal[] TestDecimalArray
		{
			get;
			set;
		}

		/// <summary>
		/// 测试stringArray
		/// </summary>
		public string[] TestStringArray
		{
			get;
			set;
		}

		/// <summary>
        /// Initializes a new instance of the <see cref="TestData"/> class.
        /// </summary>
        public TestData()
            : base()
        {
        }
    }
}